### ISSUE TITLE
Iap Error Please help me ?

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#104]
![unknown](https://user-images.githubusercontent.com/61230304/103412145-cfdc0000-4b84-11eb-9dcb-25c6c59906ef.png)

**Comment by dclgamingtr** [comment]
I entered a key, deleted it so that it would not appear in the picture.

**Comment by insthync** [comment]
Mine is working, try find and download Unity IAP from asset store
![Screenshot_269](https://user-images.githubusercontent.com/2697550/103464354-96aeb600-4d65-11eb-8d48-9416e1a06858.png)

**Comment by dclgamingtr** [comment]
![İAP](https://user-images.githubusercontent.com/61230304/103473907-adc5c600-4dae-11eb-9136-56a413132a1a.png)
The app you said is already installed. The same problem exists with a few others. I saw it on Discord server.

**Comment by insthync** [comment]
Did you try to delete the plugin (`Plugins\UDP\` and `Plugins\UnityPurchasing\` folders) then re-import?

**Comment by dclgamingtr** [comment]
First I deleted it completely. Then I re-imported it.  As you said, I deleted both and reinstalled.

**Comment by insthync** [comment]
Did you press install on the popup?, if you've installed it properly this file will be removed 
![Screenshot_277](https://user-images.githubusercontent.com/2697550/103474309-440ce280-4dd5-11eb-8055-35bfb1d4d439.png)

**Comment by insthync** [comment]
Or you may try double-click on that file (`UnityIAP`) to import the package

**Comment by dclgamingtr** [comment]
That file was deleted by itself after installation.

**Comment by dclgamingtr** [comment]
Can you connect and control remotely.

**Comment by insthync** [comment]
Okay, send your TeamViewer info to ittipon.bay@gmail.com

**Comment by insthync** [comment]
Done by, 
- Disable `Purchasing` in `Services` tab
- Import `Unity IAP` package
- Enable `Purchasing`

**Comment by dclgamingtr** [comment]
Hello, my problem is not solved I am having the same problem. After you exited from the remote connection, I started getting the same error. I'll be releasing my game soon so help please.

**Comment by dclgamingtr** [comment]
According to my research, IStoreListener unity was disabled after the 2017 release. I understand the codes need to be updated, to work in Unity 2019 Release.
