### ISSUE TITLE
Can not create Clan 

### ISSUE THREAD

**Issue by Fighterone666** [suriyun-production/turnbase-rpg-docs#176]
Hi,

in the new Version 1.18. I can no create a clan. 

The clan is written to the DB, after which it crashes with an error.

I reloaded it completely, same error.

There are no Clan Boss Stages in the Game Database either?

Error: 

GET->Error] clan HTTP/1.1 500 Internal Server Error <!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Invalid argument supplied for foreach()</p>
<pre>[fatfree/lib/base.php:2342] Base->error()
[functions/ClanBoss.php:25] Base->{closure}()
[index.php:59] CreateClanEvent()
</pre>
</body>
</html>
UnityEngine.Debug:LogError(Object)
<GetRoutine>d__7:MoveNext() (at Assets/RPGGame/Core/Scripts/GameService/Implement/WebServiceClient/WebServiceClient.cs:100)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by insthync** [comment]
Your game doesn't have clan bosses?

**Comment by insthync** [comment]
I've pushed new update, try it.

**Comment by Fighterone666** [comment]
Now it works with the clan creation. But clan bosses are still not being created. Raid bosses only.

**Comment by insthync** [comment]
Maybe because there is no clan bosses data in exported game data

**Comment by Fighterone666** [comment]
Yes that is missing. Does not exist in the database. Not even in the current version 1.18 in the Asset Store.

**Comment by insthync** [comment]
Are you sure?

**Comment by insthync** [comment]
- Did you update the service to 1.18?
- Did you update the database tables to 1.18?
- Did you export game data from the Unity project?

**Comment by insthync** [comment]
And if it's missing, what is the reason for me to add it just to show you while you can do it by yourself?

**Comment by insthync** [comment]
Or you can't? Then if you can't, you know how to add raid boss?, it's similar, just changes from raid boss to clan boss

**Comment by Fighterone666** [comment]
The option "Clan Boss Stages" is missing in the game database and I don't know how to add completely new values ​​there.

Unfortunately, the option is completely missing in the new version. A new project in Unity and only the new version 1.18. Raid Boss Stages exist, but Clan Boss Stages do not.

**Comment by insthync** [comment]
![Screenshot_596](https://user-images.githubusercontent.com/2697550/128867588-6b22b8d1-cc94-4154-9bbd-689f027c0329.png)

Don't have this?

You might have a problem with `Package manager`, I just download and import it and it is there.

It is not "completely missing in the new version". Check yours.

**Comment by Fighterone666** [comment]
Yes you were right The problem was in the package manager. There was no error, but it didn't import the latest version. I deleted it manually and then downloaded and imported it again. Now there is the option of Clan Bosses. Thank you!!!
